### ISSUE TITLE
Index view: table headings centered while switch is not

### ISSUE THREAD

**Issue by johnpuddephatt** [trin4ik/nova-switcher#1]
![Screenshot 2023-01-17 at 11 00 52](https://user-images.githubusercontent.com/8030910/212882476-b2d3863a-118d-4e89-8e25-40421909cc79.jpg)

I'm seeing the above in my index view while using this field.

My first thought was to left-align the table heading but I can't see how this is controlled.

The alternative would be to center the switch (e.g. by adding `margin: 0 auto;` to the styles for .switch). Happy to submit a PR for this but it might be that you prefer to left-align the table heading?

**Comment by trin4ik** [comment]
@johnpuddephatt , ty for feedback. 
i think, we need align column from standart properties (realize `textAlign` method https://nova.laravel.com/docs/4.0/resources/fields.html#field-text-alignment) + auto-align-center, if no labels on switchers.

**Comment by trin4ik** [comment]
done
